name: Build Thinstation ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: thinstation/thinstation:latest
      options: --privileged
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Build
        run: |
          cd /thinstation/ts
          ./build --allmodules

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: thinstation-iso
          path: /thinstation/ts/boot-images/iso/*.iso
