name: Build Thinstation ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:38
      options: --privileged
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          dnf install -y dnf-plugins-core squashfs-tools mtools genisoimage syslinux git sudo

      - name: Run Thinstation Setup and Build
        run: |
          ./setup-chroot -i -b -o --allmodules

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: thinstation-iso
          path: ts/boot-images/iso/*.iso
